### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by Bressack** [Night-squad/42-nightsquad-package#4]
[Enter steps to reproduce:]

ctrl-alt-o in loop :D
lel

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.5
**Thrown From**: [42-nightsquad-package](https://github.com/Night-squad/42-nightsquad-package) package 0.14.6

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/tharchen/.atom/packages/42-nightsquad-package/lib/nightsquad-package-view.js:296

TypeError: Cannot read property 'remove' of undefined
    at NightsquadPackageView.hideHome (/packages/42-nightsquad-package/lib/nightsquad-package-view.js:296:13)
    at NightsquadPackageView.destroy (/packages/42-nightsquad-package/lib/nightsquad-package-view.js:343:8)
    at Object.deactivate (/packages/42-nightsquad-package/lib/nightsquad-package.js:192:32)
    at Object.toggle (/packages/42-nightsquad-package/lib/nightsquad-package.js:202:8)
    at HTMLElement.nightsquadPackageToggle (/packages/42-nightsquad-package/lib/nightsquad-package.js:134:43)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284598)
```

### Commands

```
 63x -0:50.2.0 nightsquad-package:toggle (input.hidden-input)
```

### Non-Core Packages

```
42-nightsquad-package 0.14.6 
42-nightsquad-syntax 2.1.1 
42-nightsquad-ui 0.5.0 
atom-material-syntax-dark 1.0.0 
file-icons 2.1.36 
header-42 0.3.3 
highlight-selected 0.16.0 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
multi-cursor 3.0.0 
```

**Comment by SimplySka** [comment]
ok now ?
