### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: https://nightsquad.space/assets/img/federa...

### ISSUE THREAD

**Issue by Bressack** [Night-squad/42-nightsquad-package#5]
[Enter steps to reproduce:]

i've just updated the package :/

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.5
**Thrown From**: [42-nightsquad-package](https://github.com/Night-squad/42-nightsquad-package) package 1.0.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: https://nightsquad.space/assets/img/federation_ban.svg

```
At /Users/tharchen/.atom/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:1560

Error: Syntax error, unrecognized expression: https://nightsquad.space/assets/img/federation_ban.svg
    at Function.Sizzle.error (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:1560:8)
    at Sizzle.tokenize (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:2216:11)
    at Sizzle.select (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:2643:20)
    at /packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:862:9)
    at jQuery.fn.init.find (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:2896:11)
    at /packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:3006:32)
    at jQuery (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:152:10)
    at /packages/42-nightsquad-package/lib/view/home/home-coalitions-view.js:61:4)
    at HTMLImageElement.opt.complete (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:7489:12)
    at fire (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:3291:31)
    at /packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:3421:7)
    at tick (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:7332:13)
    at Function.jQuery.fx.tick (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:7658:9)
    at schedule (/packages/42-nightsquad-package/node_modules/jquery/dist/jquery.js:7035:13)
```

### Commands

```
```

### Non-Core Packages

```
42-nightsquad-package 1.0.0 
42-nightsquad-syntax 2.2.2 
42-nightsquad-ui 0.6.0 
atom-material-syntax-dark 1.0.0 
docker 0.8.0 
file-icons 2.1.36 
header-42 0.3.3 
highlight-selected 0.16.0 
ide-docker 0.1.0 
language-docker 1.1.8 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
multi-cursor 3.0.0 
```

**Comment by SimplySka** [comment]
fixed in 1.0.1 soz
